#!/usr/bin/env bash
# kit-status.sh — render the generated status view. Never hand-edit the output.
set -uo pipefail
. "$(dirname "$0")/kit-lib.sh"

ROOT=$(kit_root) || exit 0
kit_active "$ROOT" || exit 0
PROFILE=$(kit_profile "$ROOT")
STATE_DIR=$(kit_cfg "$PROFILE" paths.state ".project")
OUT="$ROOT/$(kit_cfg "$PROFILE" paths.status "STATUS.generated.md")"
DB="$ROOT/$STATE_DIR/index.db"

# `bash <script>` rather than a bare invocation: tooling/ arrives without the exec bit in
# some packagings, and a status run that silently skips its own rebuild lands squarely in
# the failure guarded against just below.
if [ ! -f "$DB" ]; then
  bash "$(dirname "$0")/kit-index.sh" >/dev/null ||
    { kit_warn "index build failed — refusing to write a status file"; exit 1; }
fi

# Prove the index is readable before rendering anything. Every query below degrades to
# empty on a missing or corrupt DB, and an empty STATUS.generated.md is indistinguishable
# from an idle repo -- a measurement failure wearing the costume of good news. The trailer
# warning at the bottom cannot catch this either, since TOTAL would default to 0.
if ! sqlite3 "$DB" "SELECT COUNT(*) FROM task;" >/dev/null 2>&1; then
  kit_warn "index at ${DB#$ROOT/} is missing or unreadable; run kit-index.sh"
  exit 1
fi

q() { sqlite3 -noheader -separator '|' "$DB" "$1" 2>/dev/null; }

TOTAL=$(q "SELECT value FROM meta WHERE key='commits_total';");    TOTAL=${TOTAL:-0}
UNTAG=$(q "SELECT value FROM meta WHERE key='commits_untagged';"); UNTAG=${UNTAG:-0}
# meta holds TEXT; a non-numeric value would make the arithmetic at the bottom fail.
case "$TOTAL" in ''|*[!0-9]*) TOTAL=0 ;; esac
case "$UNTAG" in ''|*[!0-9]*) UNTAG=0 ;; esac

{
printf '<!-- GENERATED by kit-status.sh. Do not edit. Source of truth: whatever ingest.* selects — task files and git trailers by default. -->\n'
printf '# Status\n\n'

printf '## Open\n\n'
OPEN=$(q "SELECT t.id||'  '||COALESCE(NULLIF(n.title,''),t.id)||'  ['||COALESCE(NULLIF(t.tier,''),'untiered')||']'||CASE WHEN t.blocked_by<>'' THEN '  blocked-by '||t.blocked_by ELSE '' END||CASE WHEN COALESCE(t.owner,'')<>'' THEN '  @'||t.owner ELSE '' END
          FROM task t JOIN node n ON n.id=t.id
          WHERE t.state NOT IN ('done','abandoned') ORDER BY t.state, t.id;")
[ -n "$OPEN" ] && printf '%s\n' "$OPEN" | sed 's/^/- /' || printf '_none_\n'

printf '\n## Closed\n\n'
printf -- '- %s done, %s abandoned\n' \
  "$(q "SELECT COUNT(*) FROM task WHERE state='done';")" \
  "$(q "SELECT COUNT(*) FROM task WHERE state='abandoned';")"

printf '\n## Escape rate by tier\n\n'
ESC=$(q "SELECT COALESCE(NULLIF(t.tier,''),'untiered')||'  '||
                SUM(CASE WHEN e.kind='escaped' THEN 1 ELSE 0 END)||' / '||COUNT(DISTINCT t.id)
         FROM task t LEFT JOIN event e ON e.task_id=t.id
         GROUP BY COALESCE(NULLIF(t.tier,''),'untiered') ORDER BY 1;")
[ -n "$ESC" ] && printf '%s\n' "$ESC" | sed 's/^/- /' || printf '_no data yet_\n'

if [ "$TOTAL" -gt 0 ] && [ $(( UNTAG * 100 / TOTAL )) -gt 20 ]; then
  printf '\n> **Trailer discipline degraded.** %s of %s commits carry no `Task-Id`.\n' "$UNTAG" "$TOTAL"
  printf '> Derived status under-reports; an empty backlog here may be a measurement failure, not an idle repo.\n'
fi
} > "$OUT"
echo "${OUT#$ROOT/}"
