#!/usr/bin/env bash
# kit-status.sh — render the generated status view. Never hand-edit the output.
set -uo pipefail
. "$(dirname "$0")/kit-lib.sh"

ROOT=$(kit_root) || exit 0
kit_active "$ROOT" || exit 0
PROFILE=$(kit_profile "$ROOT")
STATE_DIR=$(kit_cfg "$PROFILE" paths.state ".project")
OUT="$ROOT/$(kit_cfg "$PROFILE" paths.status "STATUS.generated.md")"
DB="$ROOT/$STATE_DIR/index.db"

# `bash <script>` rather than a bare invocation: tooling/ arrives without the exec bit in
# some packagings, and a status run that silently skips its own rebuild lands squarely in
# the failure guarded against just below.
if [ ! -f "$DB" ]; then
  bash "$(dirname "$0")/kit-index.sh" >/dev/null ||
    { kit_warn "index build failed — refusing to write a status file"; exit 1; }
fi

# Prove the index is readable before rendering anything. Every query below degrades to
# empty on a missing or corrupt DB, and an empty STATUS.generated.md is indistinguishable
# from an idle repo -- a measurement failure wearing the costume of good news. The trailer
# warning at the bottom cannot catch this either, since TOTAL would default to 0.
if ! sqlite3 "$DB" "SELECT COUNT(*) FROM task;" >/dev/null 2>&1; then
  kit_warn "index at ${DB#$ROOT/} is missing or unreadable; run kit-index.sh"
  exit 1
fi

q() { sqlite3 -noheader -separator '|' "$DB" "$1" 2>/dev/null; }

TOTAL=$(q "SELECT value FROM meta WHERE key='commits_total';");    TOTAL=${TOTAL:-0}
UNTAG=$(q "SELECT value FROM meta WHERE key='commits_untagged';"); UNTAG=${UNTAG:-0}
EXEMPTN=$(q "SELECT value FROM meta WHERE key='commits_exempt';");  EXEMPTN=${EXEMPTN:-0}
# meta holds TEXT; a non-numeric value would make the arithmetic at the bottom fail.
case "$TOTAL" in ''|*[!0-9]*) TOTAL=0 ;; esac
case "$UNTAG" in ''|*[!0-9]*) UNTAG=0 ;; esac
case "$EXEMPTN" in ''|*[!0-9]*) EXEMPTN=0 ;; esac
# The denominator is commits that were REQUIRED to carry a Task-Id, not every commit.
# git.trivial_pattern exempts chore/docs/style at the commit-msg hook, so counting them
# here made the warning permanent on a repository obeying the rule exactly. Guard against
# a stale index written before commits_exempt existed, where EXEMPTN reads 0.
REQUIRED=$(( TOTAL - EXEMPTN )); [ "$REQUIRED" -lt 0 ] && REQUIRED=0

{
printf '<!-- GENERATED by kit-status.sh. Do not edit. Source of truth: whatever ingest.* selects — task files and git trailers by default. -->\n'
printf '# Status\n\n'

printf '## Open\n\n'
OPEN=$(q "SELECT t.id||'  '||COALESCE(NULLIF(n.title,''),t.id)||'  ['||COALESCE(NULLIF(t.tier,''),'untiered')||']'||CASE WHEN t.blocked_by<>'' THEN '  blocked-by '||t.blocked_by ELSE '' END||CASE WHEN COALESCE(t.owner,'')<>'' THEN '  @'||t.owner ELSE '' END
          FROM task t JOIN node n ON n.id=t.id
          WHERE t.state NOT IN ('done','abandoned') ORDER BY t.state, t.id;")
[ -n "$OPEN" ] && printf '%s\n' "$OPEN" | sed 's/^/- /' || printf '_none_\n'

printf '\n## Closed\n\n'
printf -- '- %s done, %s abandoned\n' \
  "$(q "SELECT COUNT(*) FROM task WHERE state='done';")" \
  "$(q "SELECT COUNT(*) FROM task WHERE state='abandoned';")"

printf '\n## Escape rate by tier\n\n'
ESC=$(q "SELECT COALESCE(NULLIF(t.tier,''),'untiered')||'  '||
                SUM(CASE WHEN e.kind='escaped' THEN 1 ELSE 0 END)||' / '||COUNT(DISTINCT t.id)
         FROM task t LEFT JOIN event e ON e.task_id=t.id
         GROUP BY COALESCE(NULLIF(t.tier,''),'untiered') ORDER BY 1;")
[ -n "$ESC" ] && printf '%s\n' "$ESC" | sed 's/^/- /' || printf '_no data yet_\n'

# Cost is a function of tier, and tier is assigned before anything spawns -- so a tiered
# backlog is already a forecast. This is the other half: what it actually cost.
#
# The rate is derived from THIS project's own closed tasks, not from a table shipped with the
# kit. A rate card from someone else's codebase forecasts someone else's codebase.
SPENT=$(q "SELECT COUNT(*) FROM spend;")
if [ "${SPENT:-0}" -gt 0 ]; then
  printf '\n## Spend\n\n'
  ACT=$(q "SELECT COALESCE(NULLIF(t.tier,''),'untiered')||'  '||COUNT(DISTINCT s.task_id)||
                  ' task(s), '||(SUM(s.tok_out+s.tok_in)/1000)||'k out+in, '||
                  (SUM(s.tok_out+s.tok_in)/COUNT(DISTINCT s.task_id)/1000)||'k mean'
             FROM spend s JOIN task t ON t.id=s.task_id
            WHERE s.task_id IS NOT NULL AND s.task_id<>''
            GROUP BY COALESCE(NULLIF(t.tier,''),'untiered') ORDER BY 1;")
  [ -n "$ACT" ] && printf '%s\n' "$ACT" | sed 's/^/- /'

  # Forecast the open backlog at this project's own measured mean per tier. Tiers with no
  # closed measurement are named rather than assumed -- an estimate that silently treats an
  # unmeasured tier as free is the failure this exists to avoid.
  EST=$(q "WITH rate AS (
             SELECT t.tier AS tier, SUM(s.tok_out+s.tok_in)/COUNT(DISTINCT s.task_id) AS per
               FROM spend s JOIN task t ON t.id=s.task_id
              WHERE s.task_id IS NOT NULL AND s.task_id<>'' AND t.tier IS NOT NULL AND t.tier<>''
              GROUP BY t.tier)
           SELECT COALESCE(NULLIF(t.tier,''),'untiered')||'  '||COUNT(*)||' open x '||
                  COALESCE((SELECT (per/1000)||'k' FROM rate WHERE rate.tier=t.tier),'no rate yet')
             FROM task t WHERE t.state NOT IN ('done','abandoned')
            GROUP BY COALESCE(NULLIF(t.tier,''),'untiered') ORDER BY 1;")
  if [ -n "$EST" ]; then
    printf '\n**Open backlog at this project'"'"'s measured rate**\n\n'
    printf '%s\n' "$EST" | sed 's/^/- /'
  fi

  UNATT=$(q "SELECT COUNT(*) FROM spend WHERE task_id IS NULL OR task_id='';")
  if [ "${UNATT:-0}" -gt 0 ]; then
    printf '\n> **%s spend record(s) unattributed.** No task-status transition followed them,\n' "$UNATT"
    printf '> so they belong to no task here — the work happened, the cost is real, and it is\n'
    printf '> excluded from every figure above.\n'
  fi
fi

# Under-tiering is silent and it is the dangerous direction: a task recorded T1 that should
# be T2 gets one fewer reviewer and nothing says so. Measured on a real backlog, two of three
# recorded tiers were below their floor -- both because the backlog was tiered from finding
# SEVERITY rather than checked against the project's own tier.rule globs.
#
# Escape rate by tier is computed from these same values, so a wrong tier does not make that
# metric noisy. It makes it wrong in a direction that still looks calibrated.
BELOW=$(q "SELECT t.id||'  recorded '||COALESCE(NULLIF(t.tier,''),'(none)')||', floor '||t.tier_floor
             FROM task t
            WHERE t.tier_floor IS NOT NULL
              AND (t.tier IS NULL OR t.tier='' OR t.tier < t.tier_floor)
              AND t.state NOT IN ('done','abandoned')
            ORDER BY t.tier_floor DESC, t.id;")
if [ -n "$BELOW" ]; then
  printf '\n## Below their tier floor\n\n'
  printf '%s\n' "$BELOW" | sed 's/^/- /'
  printf '\n_A floor raises and never lowers. Reviewed one rung shallow until corrected._\n'
fi

# Silence on an unjudgeable task is how under-tiering stays invisible, so say how much of the
# backlog the check could not speak for rather than letting it read as a clean bill.
NOBASIS=$(q "SELECT COUNT(*) FROM task WHERE tier_floor IS NULL AND state NOT IN ('done','abandoned');")
OPENN=$(q "SELECT COUNT(*) FROM task WHERE state NOT IN ('done','abandoned');")
if [ "${NOBASIS:-0}" -gt 0 ]; then
  printf '\n> **Tier floors unverified for %s of %s open task(s).** No declared `paths:` and no\n' "$NOBASIS" "$OPENN"
  printf '> files touched yet, so no floor could be computed — not that none applies.\n'
fi

if [ "$REQUIRED" -gt 0 ] && [ $(( UNTAG * 100 / REQUIRED )) -gt 20 ]; then
  printf '\n> **Trailer discipline degraded.** %s of %s non-trivial commits carry no `Task-Id`' "$UNTAG" "$REQUIRED"
  [ "$EXEMPTN" -gt 0 ] && printf ' (%s trivial commit(s) excluded per `git.trivial_pattern`)' "$EXEMPTN"
  printf '.\n'
  printf '> Derived status under-reports; an empty backlog here may be a measurement failure, not an idle repo.\n'
fi
} > "$OUT"
echo "${OUT#$ROOT/}"
